name: Android CI/CD

on:
  push:
    branches:
      - Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Test Script
      run: echo "Il workflow funziona correttamente"
